name: update-gh-activity

on:
  workflow_dispatch:
  schedule:
    - cron: "7,37 * * * *"

permissions:
  contents: write

concurrency:
  group: profile-readme-updates
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
